name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        channel: [stable, beta, nightly]
        os: [ubuntu, macos, windows]
    steps:
      - uses: actions/checkout@v4.1.7

      - run: rustup default ${{ matrix.channel }}
      - run: cargo build --verbose --all-targets
      - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
